196-UIKitの学習-11.Closure
keigoakiba/UIKit-Training pull request #11
Opened 2022-09-20 05:20 UTC by keigoakiba

動作確認はシミュレーターにてお願いします
https://app.shortcut.com/sapporomobile/story/196/uikit-11-closure

2022-09-20 05:34 UTC, keigoakiba commented
※これまでの本成果物がdelegateパターンになっていなかったため、課題を独自変更し、
「APIの結果を、コールバック形式で受け取る」ようにできていればOKとしました

※また、Reloadボタンが押下された時とアプリがフォアグランドに戻ってきた時の処理内容が同じであるため、それらの処理を一つの関数 forecastHandler()としてまとめ、ViewControllerクラス内に新規作成しました


-前回からの変更点-
ViewController.swift
73行目 completion引数の追加
103行目 completion()の呼び出しを追加
42行目 completion引数の追加
154行目 completionクロージャの処理内容をトレイリング方式で記述し追加
183行目 forecastHandler()の追加
197,202行目 forecastHandler()を呼び出す方法に変更

2022-09-20 08:39 UTC, taketomato requested changes
UT が通らなくなっています。修正お願いします。

2022-09-20 08:39 UTC, taketomato commented on Training/Training/ViewController.swift
> +    func forecastHandler(_ forecast: ForecastProtocol?) {
共通化するにあたって、 `forecast` を引数にした理由はなんでしょうか？
このクラスのプロパティ(=インスタンス変数)として持っていてそれを使うのであれば、引数にする理由がないように見えました。

2022-09-20 08:39 UTC, taketomato commented on Training/Training/ViewController.swift
> +            receiveInfo = forecast.receiveInfo
Closure を使う恩恵を少しでも受けるためにも `ReceiveInfo` を Clocuse の戻り値にしてみましょうか。
戻り値にすると `YumemiForecast` のプロパティの `receiveInfo` が削除できます。

2022-09-21 07:11 UTC, keigoakiba commented on Training/Training/ViewController.swift
> +    func forecastHandler(_ forecast: ForecastProtocol?) {
updatateForecast()やdisplayForecast()でもそうしたように、UTにてdefaultForecast以外の具象クラスを引数に与えてテストすることができると考えたためでした。
ですが、forecastHandlerを今後UTで引数アリで使う見込みがなかったので、引数なしに修正します。

2022-09-21 08:12 UTC, keigoakiba commented on Training/Training/ViewController.swift
> +            receiveInfo = forecast.receiveInfo
修正しました。

2022-09-21 08:20 UTC, taketomato approved these changes
修正OK でっす！！ 🎉

2022-09-21 08:20 UTC, merged