187-UIKitの学習-2.API
keigoakiba/UIKit-Training pull request #2
Opened 2022-07-28 05:33 UTC by keigoakiba

動作確認はシミュレーターにてお願いいたします。
以下は2.APIのストーリーです。
https://app.shortcut.com/sapporomobile/story/187/uikit-2-api

2022-07-28 09:35 UTC, taketomato requested changes

2022-07-28 09:35 UTC, taketomato commented on Training/Training/ViewController.swift
> +    var icon : UIImage!
このクラスだけしか使わない変数なので `private` つけましょう

2022-07-28 09:35 UTC, taketomato commented on Training/Training/ViewController.swift
> +    var icon : UIImage!
変数名と画像の用途が一意になるので `icon` ではなく `sunnyIcon` とか `sunnyImage` とかの名前の方がベターです。

いずれの指摘も他の変数も同様です

2022-07-28 09:35 UTC, taketomato commented on Training/Training/ViewController.swift
> +    var icon : UIImage!
色を変える方法も調べてみましょう。

2022-07-29 02:14 UTC, keigoakiba commented
上記ご指摘3点、修正しました。

2022-07-29 02:17 UTC, taketomato approved these changes

2022-07-29 02:25 UTC, merged

2022-07-29 02:27 UTC, consasap12 commented on Training/Training/ViewController.swift
> +    private var rainyIcon : UIImage!
まだ未学習かもしれませんが、 IBOutlet 以外の強制アンラップは推奨されません。
それぞれ `private var sunnyIcon : UIImage?` のようにオプショナルにするのが良いかと思います

2022-07-29 02:36 UTC, taketomato commented on Training/Training/ViewController.swift
> +    private var rainyIcon : UIImage!
話しながら補足

`UIImage!` で定義してしまうと、例えば第三者がこのクラスを使って `sunnyIcon` にアクセスするとき、アンラップしなくても使えてしまう。そうするとこの変数が nil だと実行時に落ちてしまう。 = 最悪リリースして動かすまで気づかないリスクが残る。

`UIImage?` (= Optional 型)で定義しておくと、必ずアンラップが必要になるので nil アクセスは不可、実行時に落ちることはなくなる。より安全に書くことができるようになる。