190-UIKitの学習-7.Codable
keigoakiba/UIKit-Training pull request #7
Opened 2022-08-26 04:18 UTC by keigoakiba

https://app.shortcut.com/sapporomobile/story/190/uikit-7-codable
動作確認はシミュレーターにてお願いします。

2022-08-29 02:07 UTC, taketomato requested changes
指摘確認お願いします。

2022-08-29 02:07 UTC, taketomato commented on Training/Training/ViewController.swift
>              if let receiveInfoExist = receiveInfo {
この課題の範疇じゃない指摘です。

`receiveInfo` `errorMessage` が今グローバル変数(しかもミュータブル)になっています。

ミュータブルなグローバル変数は、誰がいつ変更するか全くわからない(しかもこの変数は `private` もついていないので、他のファイルの他のクラスからアクセスし放題)なので、使わないこと推奨です。

この場合は、 `YumemiForecast` のインスタンス変数にして、 `ViewController` からは `YumemiForecast` のインスタンス経由でアクセスする方が良いです。

2022-08-29 02:07 UTC, taketomato commented on Training/Training/ViewController.swift
>              if let receiveInfoExist = receiveInfo {
`Forecast` と `YumemiForecast` が分かれている理由はなんでしょう？

2022-08-29 02:07 UTC, taketomato commented on Training/Training/ViewController.swift
> -            //exceptionのルートを通っていなかったら天気画像等を表示
せっかく日時を表示するようにしたので、「2020-04-01」ではなく現在の天気を表示するようにしては？

2022-09-01 03:17 UTC, keigoakiba commented on Training/Training/ViewController.swift
>              if let receiveInfoExist = receiveInfo {
receiveInfo errorMessage について、インスタンス変数に変更しました。

>>Forecast と YumemiForecast が分かれている理由はなんでしょう？
Delegateパターンを実装したときにこのような設計になりました。
.delegateをViewControllerクラスで使いたくて、「処理を任されるクラス(YumemiForecast)」と「処理を任せるクラス(Forecast) ←delegateを設定」に分けています。

2022-09-01 03:21 UTC, keigoakiba commented on Training/Training/ViewController.swift
> -            //exceptionのルートを通っていなかったら天気画像等を表示
現在の時刻表示をやりたいと思ったのですが、課題内容的に、APIから取ってきた日時をdate型でデコードして表示させる、ということをやるべきかなと...
確かに取ってくるデータが毎回「2020-04-01」になるので面白みはないなと思っていたのですが。

現在の時刻の表示に切り替えたほうが良いでしょうかね？

2022-09-01 04:53 UTC, taketomato requested changes

2022-09-01 04:53 UTC, taketomato commented on Training/Training/ViewController.swift
> -            //exceptionのルートを通っていなかったら天気画像等を表示
私が誤解してるかもしれませんが、L.76 で自分で 2020-04-01 を指定してるから固定になってる訳ではない？
そこを現在時刻にすれば、 `APIから取ってきた日時` も現在時刻になると理解してました。

2022-09-01 04:53 UTC, taketomato commented on Training/Training/ViewController.swift
> +    var receiveInfo: ReceiveInfo? = nil
nil を代入するかしないか揃えませんか？

2022-09-05 07:50 UTC, keigoakiba commented on Training/Training/ViewController.swift
>              if let receiveInfoExist = receiveInfo {
先ほどの解説時の通り、構成を変更しています。
また、impl(前delegate)からweakを外しました。

2022-09-05 07:51 UTC, keigoakiba commented on Training/Training/ViewController.swift
> -            //exceptionのルートを通っていなかったら天気画像等を表示
現在時刻が表示されるよう修正しました。

2022-09-05 07:51 UTC, keigoakiba commented on Training/Training/ViewController.swift
> +    var receiveInfo: ReceiveInfo? = nil
共に代入しない方で揃えました。

2022-09-05 23:30 UTC, taketomato approved these changes
動作確認も OK でした。

2022-09-05 23:30 UTC, merged