Session8
keigoakiba/UIKit-Training pull request #8
Opened 2022-08-31 03:58 UTC by keigoakiba

動作確認はシミュレーターにてお願いします
https://app.shortcut.com/sapporomobile/story/192/uikit-8-notificationcenter

2022-09-01 02:34 UTC, taketomato requested changes
`Reload` をタップすると落ちます。
今まで作った機能(で動くはずの機能)が動くことは確認しましょう。(リグレッションテストと言います。)

合わせて処理の共通化もしてみてください。

2022-09-06 06:03 UTC, keigoakiba commented
処理の共通化を実施しました。

2022-09-06 06:20 UTC, taketomato requested changes

2022-09-06 06:20 UTC, taketomato commented on Training/Training/ViewController.swift
> +
不要な変更は入れないようにしましょう。
意図して入れたのであれば、削除不要です。

2022-09-06 06:20 UTC, taketomato commented on Training/Training/ViewController.swift
> +    func information() {
何をする処理かが読んでわかるメソッド名にしましょう
たとえば `updateForecast` `updateWether`

`//メイン処理のベース` というコメントも何を伝えたいのかわかりません。
適切なメソッド名になっていればコメントは不要に見えます。

2022-09-06 06:20 UTC, taketomato commented on Training/Training/ViewController.swift
> +    @IBAction func fetchWeather(_ sender: Any) {
メソッド名 `realodTapped` といった名前の方が適切です
こちらもメソッド名が適切になっていればコメント不要かと

2022-09-06 06:20 UTC, taketomato commented on Training/Training/ViewController.swift
> +    @objc func foreground(notification: Notification) {
メソッド名これでも良いですが、THETA アプリでは `willEnterForegroundNotification` イベントを補足するメソッドという意味で `handleWillEnterForeground` という名前を習慣的に使っています。

同じくコメント不要です。

2022-09-06 06:36 UTC, keigoakiba commented on Training/Training/ViewController.swift
> +
意図して追加した行ではないので、削除します

2022-09-06 06:42 UTC, keigoakiba commented on Training/Training/ViewController.swift
> +    func information() {
updateForecastにメソッド名を変更してコメントを削除します

2022-09-06 06:46 UTC, keigoakiba commented on Training/Training/ViewController.swift
> +    @objc func foreground(notification: Notification) {
なるほどです。
今からできるだけthetaアプリで使われているメソッド名に慣れておきたいのでhandleWillEnterForegroundという名前に変更させていただきます。

2022-09-06 06:50 UTC, keigoakiba commented on Training/Training/ViewController.swift
> +    @IBAction func fetchWeather(_ sender: Any) {
reloadButtonTappedにメソッド名を変更し、コメントを削除します。
また、それに合わせてcloseViewConメソッドもcloseButtonTappedに変更します。

2022-09-06 07:30 UTC, taketomato approved these changes

2022-09-06 07:31 UTC, merged