193-UIKitの学習-9UnitTest
keigoakiba/UIKit-Training pull request #9
Opened 2022-09-13 03:50 UTC by keigoakiba

動作確認はシミュレーターでお願いします。
https://app.shortcut.com/sapporomobile/story/193/uikit-9unittest

2022-09-13 05:13 UTC, nomadmonad requested changes
コメントしました。

2022-09-13 05:13 UTC, nomadmonad commented on Training/Training/ViewController.swift
> +                minTemperature.text = "\(receiveInfo.minTemperature)"
好みだけど、ここ処理は `else` 節で書かない方が読みやすくできそう。

`else` の中、L.162の `if let ...` でさらにネストしているのでインデントが深くなっています。インデントが深くなると読みづらくなりがちなので、せっかくなので外してしまいましょう。

2022-09-13 05:13 UTC, nomadmonad commented on Training/Training/ViewController.swift
> +                if let weatherIcon = weatherIcon {
ここも好みですが… `if let` でオプショナルな変数をアンラップするときは変数名を元の変数と別な名前に変えると読みやすさを上げれる場合があります。

スコープの中と外で同じ変数を使っている場合、どっちの変数を参照しているか分かりづらくなったり、最悪メモリリークのようなバグを引き起こす場合があります。

`guard let self = self else {...}` のような例外はありますが、それ以外は別な名前にする方がオススメです。

2022-09-13 05:13 UTC, nomadmonad commented on Training/Training/forecastModel.swift
> +//  forecastModel.swift
このファイルとクラス、ユニットテストでしか使わないから `TrainingTests` ターゲットでしか使わない形に変えましょう。
こう操作すると、`TrainingTests` の中だけで参照する形に変えられます。

1. ファイルを`TrainingTests`のディレクトリ・グループに移動する
1. Atribute InspecterのTarget Membershipで、`TrainingTests` にだけチェックを付ける

2022-09-13 05:13 UTC, nomadmonad commented on Training/TrainingTests/TrainingUnitTests.swift
> +    }
使わないテストケースだから消しちゃいましょう

2022-09-13 05:13 UTC, nomadmonad commented on Training/TrainingTests/TrainingUnitTests.swift
> +    }
ここも今回は使わないから消しちゃいましょう

2022-09-13 05:13 UTC, nomadmonad commented on Training/TrainingUITests/TrainingUITests.swift
> +//  TrainingUITests.swift
今回使ってないから、`TrainingUITests`系のファイルと、`TrainingUITests`のUITestも削除してしまいましょう。

2022-09-13 06:43 UTC, keigoakiba commented on Training/Training/ViewController.swift
> +                minTemperature.text = "\(receiveInfo.minTemperature)"
外しました。
前の部分でreturnしているし、そもそもelseいらなかったですね。

2022-09-13 07:05 UTC, keigoakiba commented on Training/Training/ViewController.swift
> +                if let weatherIcon = weatherIcon {
64,83,163行目のif let アンラップにおいて、それぞれ別の変数名にするよう修正しました。

2022-09-13 07:32 UTC, keigoakiba commented on Training/Training/forecastModel.swift
> +//  forecastModel.swift
1.ファイルをTrainingTestsのディレクトリ・グループに移動する
2.Atribute InspecterのTarget Membershipで、TrainingTests にだけチェックを付ける
加えて、forecastModel.swiftに @testable import Training を付加しました

2022-09-13 07:32 UTC, keigoakiba commented on Training/TrainingTests/TrainingUnitTests.swift
> +    }
削除しました。

2022-09-13 07:33 UTC, keigoakiba commented on Training/TrainingTests/TrainingUnitTests.swift
> +    }
削除しました。

2022-09-13 07:33 UTC, keigoakiba commented on Training/TrainingUITests/TrainingUITests.swift
> +//  TrainingUITests.swift
削除しました。

2022-09-14 01:11 UTC, nomadmonad approved these changes

2022-09-14 01:29 UTC, merged